name: polynot_aipartner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  uuid: ^4.5.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  audioplayers: ^6.0.0
  audio_session: ^0.1.21
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env